name: Deploy Pipeline

on:
  push:
    branches:
      - main  # Trigger when code is pushed to main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Pull latest changes

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Server
        run: |
          ssh user@your-server-ip << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Get latest code
            source venv/bin/activate  # Activate virtual environment
            pip install -r requirements.txt  # Install dependencies
            systemctl restart your-app  # Restart FastAPI app
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
